name: ROS Noetic Build CI
on: [push, pull_request]
jobs:
  build:
    name: ROS Build
    runs-on: ubuntu-20.04
    container: ros:noetic-ros-base-focal
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
    - name: Install dependencies and packages into container
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ./scripts/actions-entrypoint.sh
        ./scripts/actions-entrypoint.sh
        git submodule update --init --recursive
    - name: Build project
      run: |
        cd ~/
        cp -r $GITHUB_WORKSPACE .
        cd ${{ github.event.repository.name }}
        /bin/bash -c "source /opt/ros/noetic/setup.bash && rosdep update && rosdep install tf && catkin_make"
