name: ROS Noetic Build CI
on: [push, pull_request]
jobs:
  build:
    name: ROS Build
    runs-on: ubuntu-20.04
    container: ros:noetic-ros-base-focal
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install catkin and dependencies
      run: |
        chmod +x $GITHUB_WORKSPACE/scripts/actions-entrypoint.sh
        $GITHUB_WORKSPACE/scripts/actions-entrypoint.sh
    - name: Build project
      run: |
        cd $GITHUB_WORKSPACE/src
        catkin_make
