name: ROS Build CI

on: [push, pull_request]

jobs:
  ros-build:
    name: ROS Build
    runs-on: ubuntu-20.04

    steps:
    - name: ROS container pull
      uses: docker://ros:noetic-ros-base-focal
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: catkin_make
      run: catkin_make